// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR4GpmkVlJIr4ZAbqT_FC31Nug4yKtcMI',
    appId: '1:703068283141:web:5ed19ecf44685fc920976c',
    messagingSenderId: '703068283141',
    projectId: 'dailyscoop-a1b5f',
    authDomain: 'dailyscoop-a1b5f.firebaseapp.com',
    storageBucket: 'dailyscoop-a1b5f.firebasestorage.app',
    measurementId: 'G-GQWN92HVEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUd29GqiS02EPZ-CjArJSgWVz13Wx1J9w',
    appId: '1:703068283141:android:d22e4c11b11783ce20976c',
    messagingSenderId: '703068283141',
    projectId: 'dailyscoop-a1b5f',
    storageBucket: 'dailyscoop-a1b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpqv2Ty-LZtbULtrPARhNyOcFyhUmUnlQ',
    appId: '1:703068283141:ios:898af5bb77f66eed20976c',
    messagingSenderId: '703068283141',
    projectId: 'dailyscoop-a1b5f',
    storageBucket: 'dailyscoop-a1b5f.firebasestorage.app',
    iosClientId: '703068283141-k7vntoaleummafj73f6ev5rj4o6mag7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyscoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpqv2Ty-LZtbULtrPARhNyOcFyhUmUnlQ',
    appId: '1:703068283141:ios:898af5bb77f66eed20976c',
    messagingSenderId: '703068283141',
    projectId: 'dailyscoop-a1b5f',
    storageBucket: 'dailyscoop-a1b5f.firebasestorage.app',
    iosBundleId: 'com.example.dailyscoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR4GpmkVlJIr4ZAbqT_FC31Nug4yKtcMI',
    appId: '1:703068283141:web:d420490c197abe6f20976c',
    messagingSenderId: '703068283141',
    projectId: 'dailyscoop-a1b5f',
    authDomain: 'dailyscoop-a1b5f.firebaseapp.com',
    storageBucket: 'dailyscoop-a1b5f.firebasestorage.app',
    measurementId: 'G-R6XMX3NGD2',
  );
}